### ISSUE TITLE
Perspective transform raises error

### ISSUE THREAD

**Issue by ChargedMonk** [rmislam/PythonSIFT#11] opened 2020-05-18 18:13 UTC
I got the following error while matching two images.

`OpenCV(4.1.2) /io/opencv/modules/core/src/matmul.dispatch.cpp:531: error: (-215:Assertion failed) scn + 1 == m.cols in function 'perspectiveTransform'`

**Comment by rmislam** [comment] 2020-05-25 10:07
Hi @ChargedMonk, can you please attach your two images here so I can debug?

**Comment by ChargedMonk** [comment] 2020-05-25 15:40
Here are the two images -

[Image 1](https://drive.google.com/file/d/10RTtbNiYHbp5gkyi1peF8J-Q4Gg_rcGK/view?usp=sharing)

[Image 2](https://drive.google.com/file/d/1BxEk62EwXhEwq7O3D96lx9tJbWp6S6wi/view?usp=sharing)

**Comment by rmislam** [comment] 2020-06-13 02:17
@ChargedMonk I can't exactly reproduce your error, but I have an idea of what is happening. Probably very few keypoints are generated for your images. When I run the matching script with your images on my computer, I only generate 9 keypoints, which is enough to generate a homography. However, possibly on your machine, there are fewer than 4 keypoints generated.

**When you run `template_matching_demo.py` on your machine, what is the length of the list variable `good`?** This is the number of keypoint matches. If there are too few points, I can suggest some threshold changes in the demo script for you.

**Comment by rmislam** [comment] 2020-06-14 03:45
I also realize you must have reduced the value of `MIN_MATCH_COUNT` at the top of the script. I've set this to 10 specifically to avoid this problem. You need at least 4 keypoints to generate a unique homography, and typically around 10 keypoints for the homography to be stable. If you can't generate enough keypoints, I suggest you try higher resolution images.

I'm going to close this issue because it's not an issue with the actual code -- it's just that not enough keypoints are generated for your particular images.

**Closed by rmislam** 2020-06-14 03:45 UTC
